name: App 1 Pipeline

on:
  workflow_call:

jobs:
  start:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/app-1
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          yarn install
          echo "${{ secrets.GITHUB_TOKEN }}"
      - name: Start
        run: yarn start

  release-please:
    needs: start
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    outputs:
      app-1--tag_name: ${{ steps.release.outputs.app-1--tag_name}}
      app-1--release_created: ${{ steps.release.outputs.app-1--release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
