name: App 4 Pipeline

on:
    schedule:
        - cron: "*/1 * * * *"

jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run script
              env:
                  NAME: ${{ secrets.NAME }}
              run: apps/app-4/script.sh "${{ secrets.NAME }}"
