name: App 3 Pipeline

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/app-3
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Start
        run: go run main.go

  release-please:
    needs: build
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    outputs:
      app-3--tag_name: ${{ steps.release.outputs.app-3--tag_name}}
      app-3--release_created: ${{ steps.release.outputs.app-3--release_created}}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
